[package]
name = "arkanoid"
version = "0.1.0"
edition = "2018"

[dependencies]
arkanoid_precompile = { path = "arkanoid_precompile" }
amethyst = { version = "0.13.2", features = ["vulkan"] }
serde = "1.0.104"
serde_derive = "1.0.104"
ncollide2d = "0.20.1"
