[package]
name = "arkanoid_precompile"
version = "0.1.0"
edition = "2018"

[dependencies]
amethyst = { version = "0.13.2", features = ["vulkan"] }
serde = "1.0.104"
serde_derive = "1.0.104"
derive_more = "0.99.2"
